### ISSUE TITLE
BDD

### ISSUE THREAD

**Issue by DARTFR** [Mad-Rage/Mad-Bot#1]
Salut, quand je télécharge la BDD, je ne trouve la le point BDD. Tu peux aider STP. Le mettre en Realese ou un autre truc ?

**Comment by Mad-Rage** [comment]
C'est un robot de tuto YouTube, docn non le .sql ne sera pas mis ^^

**Comment by DARTFR** [comment]
Ok bah je vais voir d'autre github...
